# Department of Labor appreticeship program data

This short notebook analyzes data from the DoL "Apprenticeship Participant Characteristics and Training Outcomes" data, available here: https://data.dol.gov/datasets/10264

In [54]:
# Import libraries
import requests, pandas as pd, json

with open("api_key.txt", "r") as file:
    API_KEY = file.read().strip()

Metadata:

In [55]:
# def create_filter_condition(field, operator, value):
#     return {"and": [{"field": field, "operator": operator, "value": value}]}
def create_filter_condition(field, operator, value):
    condition = {"field": field, "operator": operator, "value": value}

    return json.dumps(condition)


params = {"X-API-KEY": API_KEY}

# Get metadata
metadata_url = "https://apiprod.dol.gov/v4/get/ETA/apprenticeship_data/json/metadata"
metadata_request = requests.get(metadata_url, params=params, verify=False)
metadata_json = metadata_request.json()
metadata = pd.DataFrame(metadata_json)
metadata

c:\Users\ERODRI01\OneDrive - Environmental Protection Agency (EPA)\Documents\dol-data\.venv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apiprod.dol.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,variable_id,short_name,full_name,variable_description,variable_category,variable_type,intended_datatype,application_datatype,linked_tables,universe,...,number_valueless,valueless_list,minimum,first_quartile,mean,median,third_quartile,maximum,allowed_category_counts,missing_category_counts
0,eta_oa_apprenticeship_1,fiscal_year,None,Fiscal Year the Apprentice's start date falls ...,classification,derived,categorical,number,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
1,eta_oa_apprenticeship_2,table_name,None,Indicates whether data are from the apprentice...,classification,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
2,eta_oa_apprenticeship_3,start_date,None,Date an Apprentice begins the Program,date,acquired,date,date,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
3,eta_oa_apprenticeship_4,exit_date,None,"Date an apprentice exits an apprenticeship, ei...",date,acquired,date,date,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
4,eta_oa_apprenticeship_5,apprentice_number,None,Unique ID number for each apprentice that star...,identification,acquired,text,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
5,eta_oa_apprenticeship_6,program_number,None,This is the Program Number,identification,acquired,text,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
6,eta_oa_apprenticeship_7,program_view,None,Program view indicates if a Filter was applied...,classification,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
7,eta_oa_apprenticeship_8,naics_cd,None,The North American Industry Classification Sys...,classification,inherited,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
8,eta_oa_apprenticeship_9,union_y_n,None,Indicates whether a program is Union or Non-Union,classification,derived,boolean,number,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
9,eta_oa_apprenticeship_10,apprentice_id,None,Unique identifer created when apprentices are ...,identification,acquired,numeric,number,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
10,eta_oa_apprenticeship_11,age_cohort,None,Identifies which age cohort an Apprentice belo...,classification,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
11,eta_oa_apprenticeship_12,ethnicity,None,Apprentice category that defines the apprentic...,classification,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
12,eta_oa_apprenticeship_13,gender,None,Apprentice category that defines the apprentic...,classification,acquired,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
13,eta_oa_apprenticeship_14,race,None,Apprentice category that defines the apprentic...,classification,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
14,eta_oa_apprenticeship_15,veteran_status_title,None,Apprentice category that defines the apprentic...,classification,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
15,eta_oa_apprenticeship_16,individuals_with_disabilities,None,Indicates if an apprentice identified as being...,classification,acquired,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
16,eta_oa_apprenticeship_17,industry,None,The industry under which an apprentice is work...,classification,inherited,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
17,eta_oa_apprenticeship_18,occupation,None,The occupation of the apprentice. This include...,narrative,acquired,text,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
18,eta_oa_apprenticeship_19,education,None,Indicates the highest level of Education of an...,classification,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
19,eta_oa_apprenticeship_20,apprentice_status_code,None,"Status of the Apprentice, this determines if a...",classification,acquired,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
20,eta_oa_apprenticeship_21,active_adjust,None,Any apprentice without an NAICS Code of 922140...,classification,derived,boolean,number,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
21,eta_oa_apprenticeship_22,completer_adjust,None,Any apprentice without an NAICS Code of 922140...,classification,derived,boolean,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
22,eta_oa_apprenticeship_23,exit_wage_adjust,None,Any apprentice without an NAICS Code of 922140...,measure,acquired,numeric,float,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
23,eta_oa_apprenticeship_24,new_adjust,None,Any apprentice without an NAICS Code of 922140...,classification,derived,boolean,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
24,eta_oa_apprenticeship_25,start_wage_adjust,None,Any apprentice without an NAICS Code of 922140...,measure,calculated,numeric,float,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
25,eta_oa_apprenticeship_26,hud_state,None,Indicates the U.S Department of Housing and Ur...,location,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
26,eta_oa_apprenticeship_27,county_fips,None,Federal Information Processing Series (FIPS) C...,location,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
27,eta_oa_apprenticeship_28,county_name,None,Name of county based on the County FIPS code d...,location,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
28,eta_oa_apprenticeship_29,state,None,The State where a program is registered based...,location,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
29,eta_oa_apprenticeship_30,appr_state,None,Indicates the State where the apprentice is lo...,location,acquired,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
30,eta_oa_apprenticeship_31,appr_county_fips,None,Is the COUNTY_FIPS derived on where the appren...,location,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
31,eta_oa_apprenticeship_32,appr_county_name,None,Is the COUNTY_NAME derived on where the appren...,location,derived,categorical,varchar,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
32,eta_oa_apprenticeship_33,starting_wage,None,Wage an apprentice is paid at the start of an ...,measure,calculated,numeric,float,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None
33,eta_oa_apprenticeship_34,exit_wage,None,Wage an apprentice is paid hourly when they co...,measure,calculated,numeric,float,None,apprenticeship,...,None,None,None,None,None,None,None,None,None,None

In [56]:
# Build filters as dicts, not strings
filter_1 = create_filter_condition("union_y_n", "eq", "1")
filter_2 = create_filter_condition("value", "gt", "999")
filter_3 = create_filter_condition("industry", "in", ["A", "B", "C"])
filter_4 = create_filter_condition("industry", "like", "%A%")

url = "https://apiprod.dol.gov/v4/get/ETA/apprenticeship_data/json"

headers = {"X-API-KEY": API_KEY}

params = {
    "X-API-KEY": API_KEY,
    "limit": "1000",
    "offset": "0",
    # Pass the filter as a JSON string in the query param
    "filter_object": filter_1,  # Swap filter_1 with any of the other filters (2-4) to see different results.
}

request = requests.get(url, headers=headers, params=params, verify=False)
print(f"Request is {request}")
data_json = request.json()["data"]
data = pd.DataFrame(data_json)

c:\Users\ERODRI01\OneDrive - Environmental Protection Agency (EPA)\Documents\dol-data\.venv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apiprod.dol.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Request is <Response [200]>

Preview of the data:

In [57]:
data.head()

,fiscal_year,table_name,start_date,exit_date,apprentice_number,program_number,program_view,naics_cd,union_y_n,apprentice_id,...,start_wage_adjust,hud_state,county_fips,county_name,state,appr_state,appr_county_fips,appr_county_name,starting_wage,exit_wage
0,None,None,None,None,None,None,None,NaN,1,4087214,...,0.00,NY,None,None,NY,NY,NaN,NaN,NaN,NaN
1,None,None,None,None,None,None,None,NaN,1,4157270,...,0.00,NY,None,None,NY,NY,NaN,NaN,NaN,NaN
2,None,None,None,None,None,None,None,NaN,1,4156925,...,0.00,NY,None,None,NY,NY,NaN,NaN,NaN,NaN
3,None,None,None,None,None,None,None,311511,1,4101939,...,28.72,MI,None,None,MI,MI,26085,Lake County,28.72,NaN
4,None,None,None,None,None,None,None,NaN,1,4156760,...,0.00,NY,None,None,NY,NY,NaN,NaN,NaN,NaN